version: '3.8'
services:
  email2telegram:
    build: .
    container_name: email2telegram
    env_file:
      - .env
    ports:
      - "3080:3080"
    volumes:
      - ./data:/usr/src/app/data
    restart: unless-stopped 